name: CI

on:
  push:
  - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - name: Run install.sh
      run: bash ./install.sh
